#!/bin/bash
#
#$Log: setup,v $
#Revision 1.1  2006/07/06 14:29:18  bobfcsoft
#new test
#
#

TEST_NO=b006
TEST_DESC="nameServer script test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of pretest script goes here
#

echo "Test $TEST_NO setup finished"
