#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2006/03/24 02:14:38  bobfcsoft
#new test
#
#

TEST_NO=b004
TEST_DESC="integration test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 

cd $SIMPL_HOME/bin
./fclogger -n LOGGER > $TEST_DIR/results/junk &

cd $DRDAQ_HOME/picoMgr-2.4/bin
./picoMgr \
	-n PICOMGR\
	-l LOGGER &


cd $DRDAQ_HOME/bin
./picoReader.tcl \
	-N READER \
	-p PICOMGR \
	-l LOGGER &

./picoGUI.tcl \
	-N PICOGUI \
	-p PICOMGR \
	-l LOGGER 

echo stopping stimulator unit test
$SIMPL_HOME/bin/fcslay PICOMGR
$SIMPL_HOME/bin/fcslay READER
$SIMPL_HOME/bin/fcslay PICOGUI
$SIMPL_HOME/bin/fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
