#!/bin/bash
#
#$Log: whathappened,v $
#Revision 1.1  2006/03/21 20:43:05  bobfcsoft
#b002t guiStim.tcl
#
#
#

TEST_NO=b002t
TEST_DESC="picoMgr local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/aftershot

echo "preparing results for test#$TEST_NO ... please wait" | tee $OUTFILE
date | tee -a $OUTFILE

echo "======================="		 | tee -a $OUTFILE
cat $TEST_DIR/results/test.out 		 | tee -a $OUTFILE

echo "======================="		 | tee -a $OUTFILE
echo "Here is the test output"		 | tee -a $OUTFILE

#
# You may want to grep log for signatures here
#

echo "======================="		 | tee -a $OUTFILE

echo "comparing with expected results" | tee -a $OUTFILE

echo "======================="		 | tee -a $OUTFILE

echo "done preparing results for test#$TEST_NO"
