#!/bin/bash
#
#$Log: setup_template,v $
#Revision 1.1  2006/03/08 19:15:11  bobfcsoft
#test templates
#
#

TEST_NO=xxxx
TEST_DESC="short description here"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of pretest script goes here
#

echo "Test $TEST_NO setup finished"
