#!/bin/bash
#
#$Log: setup,v $
#Revision 1.1  2006/12/21 23:26:22  jemartins
#new unit test
#
#Revision 1.1  2006/06/15 14:05:53  jemartins
#new test
#
#Revision 1.1  2006/04/27 12:46:52  jemartins
#*** empty log message ***
#
#Revision 1.1  2006/03/24 02:14:38  bobfcsoft
#new test
#
#

TEST_NO=b004
TEST_DESC="integration test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of pretest script goes here
#

echo "Test $TEST_NO setup finished"
