#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.5  2006/05/26 16:34:57  jemartins
#*** empty log message ***
#
#Revision 1.4  2006/05/03 21:33:44  bobfcsoft
#added support for file option
#
#Revision 1.3  2006/04/25 22:04:52  bobfcsoft
#GUI stub added
#
#Revision 1.2  2006/03/22 23:15:42  bobfcsoft
#added -p parameter
#
#Revision 1.1  2006/03/15 20:14:40  bobfcsoft
#picoReader unit test
#
#

TEST_NO=b003
TEST_DESC="picoReader local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 

cd $SIMPL_HOME/bin
./fclogger -n LOGGER > $TEST_DIR/results/junk &


echo "========================================="
echo "on another console change directory to"
echo ""
echo $TEST_DIR/results
echo ""
echo "and type"
echo ""
echo "tail -f junk"
echo ""
echo "========================================="

cd $DRDAQ_HOME/picoReader/bin
./picoReader.tcl \
	-N READER \
	-p PICOSIM \
	-g PICOGUI \
	-l LOGGER &

cd $DRDAQ_HOME/picoReader/bin
./picoGUISimulator \
	-n PICOGUI\
	-l LOGGER \
	-b &

./picoMgrSimulator \
	-n PICOSIM\
	-p $TEST_DIR/data \
	-l LOGGER

echo stopping stimulator unit test

$SIMPL_HOME/bin/fcslay READER
$SIMPL_HOME/bin/fcslay PICOSIM
$SIMPL_HOME/bin/fcslay PICOGUI
$SIMPL_HOME/bin/fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
