#!/bin/bash
#
#$Log: setup,v $
#Revision 1.1  2006/03/15 20:14:40  bobfcsoft
#picoReader unit test
#
#

TEST_NO=b003
TEST_DESC="picoReader local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of pretest script goes here
#

echo "Test $TEST_NO setup finished"
