#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2008/05/16 13:05:06  jemartins
#new units tests
#
#Revision 1.3  2006/06/25 14:01:40  jemartins
#*** empty log message ***
#
#Revision 1.2  2006/05/26 16:34:57  jemartins
#*** empty log message ***
#
#Revision 1.2  2006/03/20 22:20:59  bobfcsoft
#pointed at picoMgr-2.4
#
#Revision 1.1  2006/03/13 13:18:59  bobfcsoft
#picoMgr unit test
#
#

TEST_NO=j002p
TEST_DESC="phidgetMgr local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 
#cd $DRDAQ_HOME/picoDriver
#insmod pico.o

cd $SIMPL_HOME/bin
./fclogger -n LOGGER > $TEST_DIR/results/junk &

cd $DRDAQ_HOME/phidgetMgr/bin
./phidgetMgr \
	-n PHIDGET \
	-l LOGGER &

cd $DRDAQ_HOME/phighetMgr/bin
./picoStim \
	-n PHIDGETSTIM\
	-p PHIDGET\
	-l LOGGER

echo stopping stimulator unit test
$SIMPL_HOME/bin/fcslay PHIDGETSTIM
$SIMPL_HOME/bin/fcslay PHIDGET 
$SIMPL_HOME/bin/fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
