#!/bin/bash
#
#
#$Log: runtest,v $
#Revision 1.7  2006/06/25 14:01:40  jemartins
#*** empty log message ***
#
#Revision 1.6  2006/06/22 18:01:56  jemartins
#added myID
#
#Revision 1.5  2006/05/26 16:34:57  jemartins
#*** empty log message ***
#
#Revision 1.4  2006/05/24 14:31:33  jemartins
#*** empty log message ***
#
#Revision 1.3  2006/05/15 18:20:06  jemartins
#added Copyright
#
#Revision 1.2  2006/04/27 18:32:58  jemartins
#*** empty log message ***
#
#Revision 1.1  2006/04/27 12:46:52  jemartins
#*** empty log message ***
#
#Revision 1.1  2006/03/24 02:14:38  bobfcsoft
#new test
#
#

TEST_NO=j004
TEST_DESC="integration test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
#cksum $DRDAQ_HOME/picoGUI/bin/picoGUI.tcl  |  tee -a   $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 

cd $SIMPL_HOME/bin
./fclogger -n LOGGER > $TEST_DIR/results/junk &

cd $DRDAQ_HOME/picoMgr/bin
./picoMgr \
	-n PICOMGR\
	-l LOGGER &


cd $DRDAQ_HOME/picoReader/bin
./picoReader.tcl \
	-N READER \
	-g PICOGUI \
	-p PICOMGR \
	-I 10 \
	-l LOGGER &

cd $DRDAQ_HOME/picoGUI/bin
./picoGUI.tcl \
	-N PICOGUI \
	-f $SIMPL_HOME/fifo \
	-p PICOMGR \
	-I 10 \
	-l LOGGER 

echo stopping stimulator unit test

$SIMPL_HOME/bin/fcslay PICOGUI
$SIMPL_HOME/bin/fcslay READER
$SIMPL_HOME/bin/fcslay PICOMGR
$SIMPL_HOME/bin/fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
