#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2006/05/01 20:34:07  jemartins
#unit test
#
#

TEST_NO=j001
TEST_DESC="picoGUI local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 

cd $SIMPL_HOME/bin
./fclogger -n LOGGER > $TEST_DIR/results/junk &

echo "========================================="
echo "on another console type"
echo ""
echo "     auxtest b001"
echo ""
echo "to bring up the GUI"
echo ""
echo "========================================="

cd $DRDAQ_HOME/picoGUI/bin
./picoMgrSimulator \
	-n PICOSIM\
	-g DRDAQ\
	-l LOGGER

echo stopping stimulator unit test
$SIMPL_HOME/bin/fcslay PICOSIM
$SIMPL_HOME/bin/fcslay DRDAQ
$SIMPL_HOME/bin/fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
