#!/bin/bash
#
#$Log: auxtest,v $
#Revision 1.2  2006/03/20 22:20:59  bobfcsoft
#pointed at picoMgr-2.4
#
#Revision 1.1  2006/03/15 20:25:21  bobfcsoft
#guiStim auxtest
#
#

TEST_NO=b002
TEST_DESC="picoMgr local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out


cd $DRDAQ_HOME/picoMgr-2.4/bin
./guiStim \
	-n GUISTIM \
	-p PICO\
	-l LOGGER

echo stopping stimulator unit test
$SIMPL_HOME/bin/fcslay GUISTIM

echo "Test finished you can run posttest $TEST_NO for result"
