#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.2  2006/03/20 22:20:59  bobfcsoft
#pointed at picoMgr-2.4
#
#Revision 1.1  2006/03/13 13:18:59  bobfcsoft
#picoMgr unit test
#
#

TEST_NO=b002
TEST_DESC="picoMgr local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 
cd $DRDAQ_HOME/picoDriver
insmod pico.o

cd $SIMPL_HOME/bin
./fclogger -n LOGGER > $TEST_DIR/results/junk &

cd $DRDAQ_HOME/picoMgr-2.4/bin
./picoMgr \
	-n PICO \
	-l LOGGER &

cd $DRDAQ_HOME/picoMgr-2.4/bin
./picoStim \
	-n PICOSTIM\
	-p PICO\
	-l LOGGER

echo stopping stimulator unit test
$SIMPL_HOME/bin/fcslay PICOSTIM
$SIMPL_HOME/bin/fcslay PICO 
$SIMPL_HOME/bin/fcslay LOGGER
sleep 2
rmmod pico

echo "Test finished you can run posttest $TEST_NO for result"
