#!/bin/bash
#
#$Log: auxtest,v $
#Revision 1.2  2007/06/04 14:19:27  jemartins
#*** empty log message ***
#
#Revision 1.1  2007/06/01 22:21:07  jemartins
#new unit test
#
#Revision 1.2  2006/05/26 16:34:57  jemartins
#*** empty log message ***
#
#Revision 1.2  2006/03/20 22:20:59  bobfcsoft
#pointed at picoMgr-2.4
#
#Revision 1.1  2006/03/15 20:25:21  bobfcsoft
#guiStim auxtest
#
#

TEST_NO=j002
TEST_DESC="picoMgr local unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out


cd $DRDAQ_HOME/picoMgr/bin
./picoStim \
	-n PICOSTIM \
	-p PICO\
	-l LOGGER

echo stopping stimulator unit test
$SIMPL_HOME/bin/fcslay PICOSTIM

echo "Test finished you can run posttest $TEST_NO for result"
