#!/bin/bash
#
#$Log: auxtest,v $
#Revision 1.2  2006/06/16 12:05:38  jemartins
#new test
#
#

TEST_NO=j006
TEST_DESC="simpl surrogate test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
#cksum $DRDAQ_HOME/picoGUI/bin/picoGUI.tcl  |  tee -a   $OUTFILE
date | tee -a $OUTFILE

#
# bulk of test script goes here
# 

cd $SIMPL_HOME/bin
./protocolRouter &
./surrogateTcp &
./fclogger -n LOGGER > $TEST_DIR/results/junk &

cd $DRDAQ_HOME/picoMgr/bin
./picoMgr \
	-n PICOMGR\
	-l LOGGER

echo stopping stimulator unit test

killall surrogateTcp
killall protocolRouter

$SIMPL_HOME/bin/fcslay PICOMGR
$SIMPL_HOME/bin/fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
